name: nepali_calendar_plus
description: "A feature-rich flutter package for implementing a Nepali calendar system in your applications." 
version: 0.0.1
homepage: https://github.com/Saw2110/nepali_calendar.git

plugin: 
  platforms:
    android:
    ios:
    # linux:
    # macos:
    # web:
    # windows:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

